title: Tool PoC
description: POC Doc Library for NEPTL Tools
theme: just-the-docs

url: "https://gadetesta.github.io"
baseurl: "/legend-tool"

aux_links:
  Repository: "https://github.com/gadetesta/legend-tool"
